version: 2.1

jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.5
    working_directory: ~/repo
    steps:
      - checkout
      - run: 
          name: Run test
          command: ruby calculation_spec.rb


workflows:
  version: 2.1
  workflows:
    jobs:
      - test